server:
  port: 8000

spring:
  application:
    name: gateway-service

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh


logging:
  level:
    org.springframework.r2dbc: DEBUG

